"""
FASTPARK FINAL FE/FX SCENARIO SIMULATION
========================================

Purpose
-------
Build and back-test the final FE1-FE4 and FX1-FX4 ensembles using the
existing leakage-safe component scenarios defined in:

    fastpark_forecast_analysis.py
    fastpark_forecast_simulation.py

The script uses expanding-window weight selection. For every target date and
forecast horizon, weights are selected using only target dates whose actual
outcomes would already have been known at the current forecast cutoff.

Final entry candidates
----------------------
FE1 = dynamic E11 Booking Curve + E3 Last-4 Same Weekdays
FE2 = dynamic E11 Booking Curve + E14 Weekday-Month
FE3 = dynamic E11 Booking Curve + E10 Average Passenger Penetration
FE4 = dynamic E11 + E3 + E14 three-component ensemble

Final exit candidates
---------------------
FX1 = dynamic X11 Exit Booking Curve + X3 Last-4 Same Weekdays
FX2 = dynamic X12 Duration Exit Curve + X17 Weekday-Month
FX3 = dynamic X11 Exit Booking Curve + X12 Duration Exit Curve
FX4 = dynamic X11 + X12 + X17 three-component ensemble

Important
---------
The component forecasts are generated by the existing scenario functions.
This script does not duplicate their business logic.

This script always reloads the source data and reruns the required component
scenarios from the existing forecasting engine. It does not read forecasts from
a previous Excel simulation workbook.
"""

from __future__ import annotations

import sys
import pathlib
import time
from pathlib import Path
from typing import Iterable

import numpy as np
import pandas as pd


# =============================================================================
# 0. PROJECT IMPORTS
# =============================================================================

PROJECT_ROOT = pathlib.Path(__file__).resolve().parents[1]

if str(PROJECT_ROOT) not in sys.path:
    sys.path.append(str(PROJECT_ROOT))

from modules.utils.progress import step

import scripts.fastpark_forecast_simulation as base_sim
from scripts.fastpark_forecast_analysis import (
    get_airportx_bookings_for_assets,
    clean_bookings,
)


# =============================================================================
# 1. CONFIGURATION
# =============================================================================

def get_final_scenario_config() -> dict:
    """Return the complete FE/FX simulation configuration."""

    return {
        # ------------------------------------------------------------------
        # OUTPUT
        # ------------------------------------------------------------------
        "output_path": (
            PROJECT_ROOT
            / "outputs"
            / "fastpark_final_price_scenario_simulation.xlsx"
        ),

        # ------------------------------------------------------------------
        # WEIGHT SELECTION
        # ------------------------------------------------------------------
        "weight_grid": [
            round(value, 2)
            for value in np.arange(0.0, 1.001, 0.05)
        ],

        # A candidate begins selecting weights once this many fully completed
        # historical target dates are available for the same horizon.
        "minimum_training_observations": 30,

        # Until enough history exists, use the primary component only.
        # This preserves full forecast coverage without using future data.
        "fallback_primary_weight": 1.0,

        # WAPE is the primary selection metric. MAE is used as the tie-break.
        "selection_metric": "wape",

        # ------------------------------------------------------------------
        # COMPONENT SCENARIOS
        # ------------------------------------------------------------------
        "required_entry_components": [
            "E3",
            "E10",
            "E11",
            "E14",
        ],

        "required_exit_components": [
            "X3",
            "X11",
            "X12",
            "X17",
        ],

        # ------------------------------------------------------------------
        # PRICING OVERLAY SIMULATION
        # ------------------------------------------------------------------

        "enable_pricing_simulation": True,

        "price_analysis_assets": [
            "FastPark",
            "Long Stay",
            "Mid Stay",
            "Multi",
            "Plane Parking",
            "Terminal",
        ],

        "fastpark_asset_name": "FastPark",

        "competitor_asset_names": [
            "Long Stay",
            "Mid Stay",
            "Multi",
            "Plane Parking",
            "Terminal",
        ],

        # Historical booked prices act as a proxy for the quote prices that
        # will be available to the future operational forecast.
        #
        # Start with bookings created during the 7 days ending at the cutoff.
        # If that is too sparse, widen to 14 and then 28 days.
        "pricing_created_lookback_days": [7, 14, 28],

        # Try the exact target entry date first. If insufficient product-price
        # observations exist, allow nearby target entry dates.
        "pricing_target_date_tolerance_days": 7,

        # Minimum observations required for a product price to be considered
        # representative within a pricing snapshot.
        "minimum_price_observations_per_asset": 3,

        # A FastPark price plus at least one competitor price is required.
        "minimum_competitors_available": 1,

        # Minimum earlier, completed target dates required to fit a pricing
        # adjustment at a particular horizon.
        "minimum_pricing_training_observations": 30,

        # Do not try to price-adjust a forecast where virtually all demand is
        # already visible in known bookings.
        "minimum_remaining_pickup": 10.0,

        # Bound the pricing adjustment to protect against sparse-data effects.
        "minimum_pricing_factor": 0.50,
        "maximum_pricing_factor": 1.50,

        # Bound abnormal relative-price values before fitting.
        "minimum_relative_price_index": 0.50,
        "maximum_relative_price_index": 1.50,

        "pricing_scenarios": [
            {
                "scenario_id": "PE1",
                "scenario_name": "Winning FE + Relative Price",
                "features": [
                    "relative_price_deviation",
                ],
                "description": (
                    "Adjusts the remaining entry pickup from the winning FE "
                    "forecast using FastPark price per day relative to the "
                    "median available competitor price per day."
                ),
            },
            {
                "scenario_id": "PE2",
                "scenario_name": "Winning FE + Observed Market Share",
                "features": [
                    "share_deviation",
                ],
                "description": (
                    "Adjusts the remaining entry pickup using FastPark's "
                    "share of all car-park bookings visible at the cutoff."
                ),
            },
            {
                "scenario_id": "PE3",
                "scenario_name": "Winning FE + Price and Market Share",
                "features": [
                    "relative_price_deviation",
                    "share_deviation",
                ],
                "description": (
                    "Adjusts remaining pickup using relative price position "
                    "and visible FastPark market share together."
                ),
            },
        ],

        # ------------------------------------------------------------------
        # FINAL SCENARIO DEFINITIONS
        # ------------------------------------------------------------------
        "two_component_scenarios": [
            {
                "scenario_id": "FE1",
                "scenario_name": "Dynamic Entry Booking + Weekday",
                "flow_type": "ENTRY",
                "primary": "E11",
                "comparison": "E3",
                "description": (
                    "Expanding-window weighted blend of entry booking "
                    "visibility and the average of the previous four same "
                    "weekdays."
                ),
            },
            {
                "scenario_id": "FE2",
                "scenario_name": "Dynamic Entry Booking + Weekday-Month",
                "flow_type": "ENTRY",
                "primary": "E11",
                "comparison": "E14",
                "description": (
                    "Expanding-window weighted blend of entry booking "
                    "visibility and same-weekday-same-month actual entries."
                ),
            },
            {
                "scenario_id": "FE3",
                "scenario_name": "Dynamic Entry Booking + Avg Penetration",
                "flow_type": "ENTRY",
                "primary": "E11",
                "comparison": "E10",
                "description": (
                    "Expanding-window weighted blend of entry booking "
                    "visibility and average historical passenger penetration."
                ),
            },
            {
                "scenario_id": "FX1",
                "scenario_name": "Dynamic Exit Booking + Weekday",
                "flow_type": "EXIT",
                "primary": "X11",
                "comparison": "X3",
                "description": (
                    "Expanding-window weighted blend of exit booking "
                    "visibility and the average of the previous four same "
                    "weekdays."
                ),
            },
            {
                "scenario_id": "FX2",
                "scenario_name": "Dynamic Exit Duration + Weekday-Month",
                "flow_type": "EXIT",
                "primary": "X12",
                "comparison": "X17",
                "description": (
                    "Expanding-window weighted blend of the duration-adjusted "
                    "exit booking curve and same-weekday-same-month exits."
                ),
            },
            {
                "scenario_id": "FX3",
                "scenario_name": "Dynamic Exit Booking + Duration",
                "flow_type": "EXIT",
                "primary": "X11",
                "comparison": "X12",
                "description": (
                    "Expanding-window weighted blend of the standard and "
                    "duration-adjusted exit booking curves."
                ),
            },
        ],

        "three_component_scenarios": [
            {
                "scenario_id": "FE4",
                "scenario_name": "Dynamic Entry Three-Component Ensemble",
                "flow_type": "ENTRY",
                "components": ["E11", "E3", "E14"],
                "description": (
                    "Expanding-window three-component blend of entry booking "
                    "visibility, four-same-weekday entries, and weekday-month "
                    "entries."
                ),
            },
            {
                "scenario_id": "FX4",
                "scenario_name": "Dynamic Exit Three-Component Ensemble",
                "flow_type": "EXIT",
                "components": ["X11", "X12", "X17"],
                "description": (
                    "Expanding-window three-component blend of exit booking "
                    "visibility, duration-adjusted exits, and weekday-month "
                    "exits."
                ),
            },
        ],
    }


# =============================================================================
# 2. SOURCE COMPONENT DATA
# =============================================================================

def validate_component_results(component_results: pd.DataFrame, config: dict) -> None:
    """Validate that all required source scenarios and columns are present."""

    required_columns = [
        "target_date",
        "cutoff_timestamp",
        "horizon_days",
        "demand_type",
        "scenario_id",
        "forecast_value",
        "actual_value",
    ]

    missing_columns = [
        column
        for column in required_columns
        if column not in component_results.columns
    ]

    if missing_columns:
        raise RuntimeError(
            "Component results are missing required columns: "
            + ", ".join(missing_columns)
        )

    expected = set(
        config["required_entry_components"]
        + config["required_exit_components"]
    )

    found = set(component_results["scenario_id"].dropna().unique())
    missing_scenarios = sorted(expected - found)

    if missing_scenarios:
        raise RuntimeError(
            "Source simulation is missing required component scenarios: "
            + ", ".join(missing_scenarios)
        )

    duplicates = (
        component_results
        .duplicated(
            subset=[
                "target_date",
                "horizon_days",
                "demand_type",
                "scenario_id",
            ],
            keep=False,
        )
        .sum()
    )

    if duplicates:
        raise RuntimeError(
            f"Component results contain {duplicates:,} duplicate rows at "
            "target/horizon/flow/scenario grain."
        )


def regenerate_component_results(config: dict) -> pd.DataFrame:
    """
    Reload source data and regenerate only the scenarios required by FE/FX.

    This route reuses all source data loading, cleaning, cache building and
    scenario functions from fastpark_forecast_simulation.py.
    """

    base_config = base_sim.get_final_simulation_config()
    base_config["smoke_test"] = False
    base_config["fail_fast"] = True

    print("Loading and preparing source forecasting data...")

    raw_data = base_sim.load_simulation_data(base_config)
    base_sim.validate_loaded_data(raw_data, base_config)

    print("Loading multi-product bookings for pricing simulation...")

    pricing_bookings_raw = get_airportx_bookings_for_assets(
        start=base_config["history_start"],
        end=base_config["history_end"],
        statuses=["B", "CX", "F"],
        asset_names=config["price_analysis_assets"],
        engine=None,
    )

    pricing_bookings = clean_bookings(
        pricing_bookings_raw,
        base_config,
    )

    model_data = base_sim.prepare_forecast_model_data(
        data=raw_data,
        config=base_config,
    )

    test_dates = base_sim.create_test_dates(base_config)
    horizons = base_config["forecast_horizons_days"]

    entry_ids = config["required_entry_components"]
    exit_ids = config["required_exit_components"]

    all_rows = []
    total_snapshots = len(test_dates) * len(horizons)
    counter = 0

    print("\nGenerating required FE/FX source components...")

    for target_date in pd.to_datetime(test_dates["target_date"]).dt.normalize():
        for horizon_days in horizons:
            counter += 1

            print(
                f"\rComponents {counter:,}/{total_snapshots:,} "
                f"| Target {target_date.date()} | T-{horizon_days}",
                end="",
            )

            cutoff_timestamp = (
                target_date
                - pd.Timedelta(days=horizon_days)
                + pd.Timedelta(hours=7)
            )

            components = base_sim.build_snapshot_components(
                target_date=target_date,
                horizon_days=horizon_days,
                data=model_data,
            )

            model_data["current_snapshot_components"] = components

            for scenario_id in entry_ids:
                forecast, diagnostics = base_sim.forecast_entry_scenario(
                    scenario_id=scenario_id,
                    target_date=target_date,
                    cutoff_timestamp=cutoff_timestamp,
                    data=model_data,
                )

                all_rows.append(
                    {
                        "target_date": target_date,
                        "cutoff_timestamp": cutoff_timestamp,
                        "horizon_days": horizon_days,
                        "demand_type": "entry",
                        "scenario_id": scenario_id,
                        "forecast_value": forecast,
                        **diagnostics,
                    }
                )

            for scenario_id in exit_ids:
                forecast, diagnostics = base_sim.forecast_exit_scenario(
                    scenario_id=scenario_id,
                    target_date=target_date,
                    cutoff_timestamp=cutoff_timestamp,
                    data=model_data,
                )

                all_rows.append(
                    {
                        "target_date": target_date,
                        "cutoff_timestamp": cutoff_timestamp,
                        "horizon_days": horizon_days,
                        "demand_type": "exit",
                        "scenario_id": scenario_id,
                        "forecast_value": forecast,
                        **diagnostics,
                    }
                )

            model_data.pop("current_snapshot_components", None)

    print()

    component_results = pd.DataFrame(all_rows)

    actuals = model_data["daily_actuals"].copy()
    actuals["target_date"] = pd.to_datetime(
        actuals["date"],
        errors="coerce",
    ).dt.normalize()

    component_results = component_results.merge(
        actuals[["target_date", "entries", "exits"]],
        on="target_date",
        how="left",
    )

    component_results["actual_value"] = np.where(
        component_results["demand_type"].eq("entry"),
        component_results["entries"],
        component_results["exits"],
    )

    component_results = component_results.drop(
        columns=["entries", "exits"],
        errors="ignore",
    )

    validate_component_results(component_results, config)

    simulation_context = {
        "raw_data": raw_data,
        "model_data": model_data,
        "base_config": base_config,
        "test_dates": test_dates,
        "horizons": horizons,
        "pricing_bookings": pricing_bookings,
    }

    return component_results, simulation_context


def get_component_results(
    config: dict,
) -> tuple[pd.DataFrame, dict]:
    """Reload all source data and rerun the required component forecasts."""

    return regenerate_component_results(config)


# =============================================================================
# 3. FORECAST MATRIX
# =============================================================================

def create_forecast_matrix(component_results: pd.DataFrame) -> pd.DataFrame:
    """Create one row per target date, cutoff, horizon and flow."""

    matrix = component_results.pivot_table(
        index=[
            "target_date",
            "cutoff_timestamp",
            "horizon_days",
            "demand_type",
            "actual_value",
        ],
        columns="scenario_id",
        values="forecast_value",
        aggfunc="first",
    ).reset_index()

    matrix.columns.name = None
    matrix["flow_type"] = np.where(
        matrix["demand_type"].eq("entry"),
        "ENTRY",
        "EXIT",
    )

    return matrix.sort_values(
        ["flow_type", "horizon_days", "target_date"]
    ).reset_index(drop=True)


# =============================================================================
# 4. WEIGHT GRIDS
# =============================================================================

def create_three_component_weight_grid(weight_grid: Iterable[float]) -> list[tuple[float, float, float]]:
    """Return all non-negative three-component weights summing to one."""

    values = sorted(set(round(float(value), 10) for value in weight_grid))
    combinations = []

    for weight_1 in values:
        for weight_2 in values:
            weight_3 = round(1.0 - weight_1 - weight_2, 10)

            if weight_3 < 0:
                continue

            if weight_3 not in values:
                continue

            combinations.append((weight_1, weight_2, weight_3))

    return combinations


def weighted_forecast_two(
    primary: pd.Series,
    comparison: pd.Series,
    primary_weight: float,
) -> pd.Series:
    """Blend two forecasts, falling back to the available component."""

    comparison_weight = 1.0 - primary_weight

    output = (
        primary_weight * primary
        + comparison_weight * comparison
    )

    output = output.where(~primary.isna(), comparison)
    output = output.where(~comparison.isna(), primary)

    return output.clip(lower=0)


def weighted_forecast_three(
    component_1: pd.Series,
    component_2: pd.Series,
    component_3: pd.Series,
    weights: tuple[float, float, float],
) -> pd.Series:
    """Blend three forecasts and renormalise across available components."""

    frame = pd.DataFrame(
        {
            "c1": component_1,
            "c2": component_2,
            "c3": component_3,
        }
    )

    weight_array = np.array(weights, dtype=float)
    available = frame.notna().to_numpy(dtype=float)
    values = frame.fillna(0).to_numpy(dtype=float)

    effective_weights = available * weight_array
    denominator = effective_weights.sum(axis=1)
    numerator = (values * effective_weights).sum(axis=1)

    result = np.divide(
        numerator,
        denominator,
        out=np.full(len(frame), np.nan, dtype=float),
        where=denominator > 0,
    )

    return pd.Series(result, index=frame.index).clip(lower=0)


# =============================================================================
# 5. WEIGHT SCORING AND SELECTION
# =============================================================================

def calculate_candidate_metrics(actual: pd.Series, forecast: pd.Series) -> dict:
    """Calculate the selection and reporting metrics for one candidate."""

    valid = actual.notna() & forecast.notna()
    actual_valid = actual.loc[valid].astype(float)
    forecast_valid = forecast.loc[valid].astype(float)

    if actual_valid.empty:
        return {
            "observations": 0,
            "wape_pct": np.nan,
            "mae": np.nan,
            "rmse": np.nan,
            "bias": np.nan,
        }

    error = forecast_valid - actual_valid
    denominator = actual_valid.abs().sum()

    return {
        "observations": int(len(actual_valid)),
        "wape_pct": (
            error.abs().sum() / denominator * 100
            if denominator > 0
            else np.nan
        ),
        "mae": float(error.abs().mean()),
        "rmse": float(np.sqrt(error.pow(2).mean())),
        "bias": float(error.mean()),
    }


def select_best_two_component_weight(
    training: pd.DataFrame,
    primary: str,
    comparison: str,
    weight_grid: list[float],
    minimum_observations: int,
    fallback_weight: float,
) -> dict:
    """Select the best two-component weight on historical training rows."""

    if len(training) < minimum_observations:
        return {
            "primary_weight": fallback_weight,
            "comparison_weight": 1.0 - fallback_weight,
            "training_observations": len(training),
            "training_wape_pct": np.nan,
            "training_mae": np.nan,
            "weight_source": "fallback_insufficient_history",
        }

    candidate_rows = []

    for primary_weight in weight_grid:
        forecast = weighted_forecast_two(
            training[primary],
            training[comparison],
            primary_weight,
        )

        metrics = calculate_candidate_metrics(
            training["actual_value"],
            forecast,
        )

        candidate_rows.append(
            {
                "primary_weight": primary_weight,
                "comparison_weight": 1.0 - primary_weight,
                **metrics,
            }
        )

    candidates = pd.DataFrame(candidate_rows)
    candidates = candidates[candidates["observations"] >= minimum_observations]

    if candidates.empty:
        return {
            "primary_weight": fallback_weight,
            "comparison_weight": 1.0 - fallback_weight,
            "training_observations": len(training),
            "training_wape_pct": np.nan,
            "training_mae": np.nan,
            "weight_source": "fallback_no_valid_candidate",
        }

    winner = candidates.sort_values(
        ["wape_pct", "mae", "primary_weight"],
        ascending=[True, True, False],
    ).iloc[0]

    return {
        "primary_weight": float(winner["primary_weight"]),
        "comparison_weight": float(winner["comparison_weight"]),
        "training_observations": int(winner["observations"]),
        "training_wape_pct": float(winner["wape_pct"]),
        "training_mae": float(winner["mae"]),
        "weight_source": "expanding_window_selected",
    }


def select_best_three_component_weights(
    training: pd.DataFrame,
    components: list[str],
    weight_combinations: list[tuple[float, float, float]],
    minimum_observations: int,
) -> dict:
    """Select the best three-component weights on historical training rows."""

    if len(training) < minimum_observations:
        return {
            "weight_1": 1.0,
            "weight_2": 0.0,
            "weight_3": 0.0,
            "training_observations": len(training),
            "training_wape_pct": np.nan,
            "training_mae": np.nan,
            "weight_source": "fallback_insufficient_history",
        }

    candidate_rows = []

    for weights in weight_combinations:
        forecast = weighted_forecast_three(
            training[components[0]],
            training[components[1]],
            training[components[2]],
            weights,
        )

        metrics = calculate_candidate_metrics(
            training["actual_value"],
            forecast,
        )

        candidate_rows.append(
            {
                "weight_1": weights[0],
                "weight_2": weights[1],
                "weight_3": weights[2],
                **metrics,
            }
        )

    candidates = pd.DataFrame(candidate_rows)
    candidates = candidates[candidates["observations"] >= minimum_observations]

    if candidates.empty:
        return {
            "weight_1": 1.0,
            "weight_2": 0.0,
            "weight_3": 0.0,
            "training_observations": len(training),
            "training_wape_pct": np.nan,
            "training_mae": np.nan,
            "weight_source": "fallback_no_valid_candidate",
        }

    winner = candidates.sort_values(
        ["wape_pct", "mae", "weight_1"],
        ascending=[True, True, False],
    ).iloc[0]

    return {
        "weight_1": float(winner["weight_1"]),
        "weight_2": float(winner["weight_2"]),
        "weight_3": float(winner["weight_3"]),
        "training_observations": int(winner["observations"]),
        "training_wape_pct": float(winner["wape_pct"]),
        "training_mae": float(winner["mae"]),
        "weight_source": "expanding_window_selected",
    }


# =============================================================================
# 6. EXPANDING-WINDOW FINAL SCENARIOS
# =============================================================================

def completed_training_rows(horizon_frame: pd.DataFrame, cutoff_timestamp: pd.Timestamp) -> pd.DataFrame:
    """
    Return rows whose target date was complete before the current cutoff.

    This deliberately requires target_date < cutoff_date. The current target
    and any target whose outcome was not complete are excluded.
    """

    cutoff_date = pd.Timestamp(cutoff_timestamp).normalize()

    return horizon_frame[
        horizon_frame["target_date"].lt(cutoff_date)
        & horizon_frame["actual_value"].notna()
    ].copy()


def run_two_component_final_scenario(
    matrix: pd.DataFrame,
    specification: dict,
    config: dict,
) -> pd.DataFrame:
    """Run one leakage-safe two-component FE/FX scenario."""

    flow_type = specification["flow_type"]
    primary = specification["primary"]
    comparison = specification["comparison"]

    flow_data = matrix[matrix["flow_type"].eq(flow_type)].copy()
    output_rows = []

    for horizon_days, horizon_frame in flow_data.groupby("horizon_days"):
        horizon_frame = horizon_frame.sort_values("target_date").copy()

        for current in horizon_frame.itertuples(index=False):
            training = completed_training_rows(
                horizon_frame,
                current.cutoff_timestamp,
            )

            selection = select_best_two_component_weight(
                training=training,
                primary=primary,
                comparison=comparison,
                weight_grid=config["weight_grid"],
                minimum_observations=config["minimum_training_observations"],
                fallback_weight=config["fallback_primary_weight"],
            )

            primary_value = getattr(current, primary)
            comparison_value = getattr(current, comparison)

            forecast = weighted_forecast_two(
                pd.Series([primary_value]),
                pd.Series([comparison_value]),
                selection["primary_weight"],
            ).iloc[0]

            output_rows.append(
                {
                    "target_date": current.target_date,
                    "cutoff_timestamp": current.cutoff_timestamp,
                    "horizon_days": int(horizon_days),
                    "horizon_label": f"T-{int(horizon_days)}",
                    "demand_type": current.demand_type,
                    "flow_type": flow_type,
                    "scenario_id": specification["scenario_id"],
                    "scenario_name": specification["scenario_name"],
                    "scenario_family": "Final Dynamic Ensemble",
                    "scenario_description": specification["description"],
                    "component_1": primary,
                    "component_1_forecast": primary_value,
                    "component_1_weight": selection["primary_weight"],
                    "component_2": comparison,
                    "component_2_forecast": comparison_value,
                    "component_2_weight": selection["comparison_weight"],
                    "component_3": None,
                    "component_3_forecast": np.nan,
                    "component_3_weight": 0.0,
                    "training_observations": selection["training_observations"],
                    "training_wape_pct": selection["training_wape_pct"],
                    "training_mae": selection["training_mae"],
                    "weight_source": selection["weight_source"],
                    "forecast_value": forecast,
                    "actual_value": current.actual_value,
                }
            )

    return pd.DataFrame(output_rows)


def run_three_component_final_scenario(
    matrix: pd.DataFrame,
    specification: dict,
    config: dict,
    weight_combinations: list[tuple[float, float, float]],
) -> pd.DataFrame:
    """Run one leakage-safe three-component FE/FX scenario."""

    flow_type = specification["flow_type"]
    components = specification["components"]

    flow_data = matrix[matrix["flow_type"].eq(flow_type)].copy()
    output_rows = []

    for horizon_days, horizon_frame in flow_data.groupby("horizon_days"):
        horizon_frame = horizon_frame.sort_values("target_date").copy()

        for current in horizon_frame.itertuples(index=False):
            training = completed_training_rows(
                horizon_frame,
                current.cutoff_timestamp,
            )

            selection = select_best_three_component_weights(
                training=training,
                components=components,
                weight_combinations=weight_combinations,
                minimum_observations=config["minimum_training_observations"],
            )

            values = [getattr(current, component) for component in components]
            weights = (
                selection["weight_1"],
                selection["weight_2"],
                selection["weight_3"],
            )

            forecast = weighted_forecast_three(
                pd.Series([values[0]]),
                pd.Series([values[1]]),
                pd.Series([values[2]]),
                weights,
            ).iloc[0]

            output_rows.append(
                {
                    "target_date": current.target_date,
                    "cutoff_timestamp": current.cutoff_timestamp,
                    "horizon_days": int(horizon_days),
                    "horizon_label": f"T-{int(horizon_days)}",
                    "demand_type": current.demand_type,
                    "flow_type": flow_type,
                    "scenario_id": specification["scenario_id"],
                    "scenario_name": specification["scenario_name"],
                    "scenario_family": "Final Dynamic Ensemble",
                    "scenario_description": specification["description"],
                    "component_1": components[0],
                    "component_1_forecast": values[0],
                    "component_1_weight": weights[0],
                    "component_2": components[1],
                    "component_2_forecast": values[1],
                    "component_2_weight": weights[1],
                    "component_3": components[2],
                    "component_3_forecast": values[2],
                    "component_3_weight": weights[2],
                    "training_observations": selection["training_observations"],
                    "training_wape_pct": selection["training_wape_pct"],
                    "training_mae": selection["training_mae"],
                    "weight_source": selection["weight_source"],
                    "forecast_value": forecast,
                    "actual_value": current.actual_value,
                }
            )

    return pd.DataFrame(output_rows)


def run_final_scenario_tournament(
    component_results: pd.DataFrame,
    config: dict,
) -> pd.DataFrame:
    """Run FE1-FE4 and FX1-FX4."""

    matrix = create_forecast_matrix(component_results)
    three_weight_grid = create_three_component_weight_grid(config["weight_grid"])

    output_frames = []

    print("\nRunning final FE/FX expanding-window tournament...")

    for specification in config["two_component_scenarios"]:
        print(
            f"  Running {specification['scenario_id']} | "
            f"{specification['scenario_name']}"
        )

        output_frames.append(
            run_two_component_final_scenario(
                matrix=matrix,
                specification=specification,
                config=config,
            )
        )

    for specification in config["three_component_scenarios"]:
        print(
            f"  Running {specification['scenario_id']} | "
            f"{specification['scenario_name']}"
        )

        output_frames.append(
            run_three_component_final_scenario(
                matrix=matrix,
                specification=specification,
                config=config,
                weight_combinations=three_weight_grid,
            )
        )

    results = pd.concat(output_frames, ignore_index=True)

    results["error"] = results["forecast_value"] - results["actual_value"]
    results["absolute_error"] = results["error"].abs()
    results["squared_error"] = results["error"].pow(2)
    results["absolute_percentage_error"] = (
        results["absolute_error"]
        / results["actual_value"].abs().replace(0, np.nan)
    )
    results["weekday"] = results["target_date"].dt.day_name()
    results["weekday_num"] = results["target_date"].dt.weekday
    results["month"] = results["target_date"].dt.month
    results["year_month"] = results["target_date"].dt.to_period("M").astype(str)

    return results


# =============================================================================
# 7. PERFORMANCE AND RANKING
# =============================================================================

def score_final_scenarios(final_results: pd.DataFrame) -> pd.DataFrame:
    """Score every FE/FX scenario at every horizon."""

    rows = []

    for (
        flow_type,
        scenario_id,
        scenario_name,
        horizon_days,
    ), group in final_results.groupby(
        ["flow_type", "scenario_id", "scenario_name", "horizon_days"]
    ):
        metrics = calculate_candidate_metrics(
            group["actual_value"],
            group["forecast_value"],
        )

        rows.append(
            {
                "flow_type": flow_type,
                "scenario_id": scenario_id,
                "scenario_name": scenario_name,
                "horizon_days": horizon_days,
                "horizon_label": f"T-{horizon_days}",
                **metrics,
                "coverage_pct": group["forecast_value"].notna().mean() * 100,
                "fallback_forecasts": int(
                    group["weight_source"].str.startswith("fallback").sum()
                ),
                "expanding_selected_forecasts": int(
                    group["weight_source"].eq("expanding_window_selected").sum()
                ),
            }
        )

    performance = pd.DataFrame(rows)

    performance["wape_rank"] = (
        performance
        .groupby(["flow_type", "horizon_days"])["wape_pct"]
        .rank(method="min", ascending=True)
    )

    return performance.sort_values(
        ["flow_type", "horizon_days", "wape_rank", "scenario_id"]
    ).reset_index(drop=True)


def create_best_final_by_horizon(performance: pd.DataFrame) -> pd.DataFrame:
    """Select the best FE and FX scenario at every horizon."""

    return (
        performance
        .sort_values(
            ["flow_type", "horizon_days", "wape_pct", "mae", "scenario_id"]
        )
        .groupby(["flow_type", "horizon_days"], as_index=False)
        .first()
        .sort_values(["flow_type", "horizon_days"])
        .reset_index(drop=True)
    )


def create_weight_summary(final_results: pd.DataFrame) -> pd.DataFrame:
    """Summarise selected FE/FX weights by scenario and horizon."""

    rows = []

    for (
        flow_type,
        scenario_id,
        scenario_name,
        horizon_days,
    ), group in final_results.groupby(
        ["flow_type", "scenario_id", "scenario_name", "horizon_days"]
    ):
        row = {
            "flow_type": flow_type,
            "scenario_id": scenario_id,
            "scenario_name": scenario_name,
            "horizon_days": horizon_days,
            "horizon_label": f"T-{horizon_days}",
            "observations": len(group),
            "expanding_selected_forecasts": int(
                group["weight_source"].eq("expanding_window_selected").sum()
            ),
            "fallback_forecasts": int(
                group["weight_source"].str.startswith("fallback").sum()
            ),
            "median_training_observations": group["training_observations"].median(),
            "component_1": group["component_1"].iloc[0],
            "component_1_mean_weight": group["component_1_weight"].mean(),
            "component_1_median_weight": group["component_1_weight"].median(),
            "component_1_min_weight": group["component_1_weight"].min(),
            "component_1_max_weight": group["component_1_weight"].max(),
            "component_2": group["component_2"].iloc[0],
            "component_2_mean_weight": group["component_2_weight"].mean(),
            "component_2_median_weight": group["component_2_weight"].median(),
            "component_2_min_weight": group["component_2_weight"].min(),
            "component_2_max_weight": group["component_2_weight"].max(),
            "component_3": group["component_3"].iloc[0],
            "component_3_mean_weight": group["component_3_weight"].mean(),
            "component_3_median_weight": group["component_3_weight"].median(),
            "component_3_min_weight": group["component_3_weight"].min(),
            "component_3_max_weight": group["component_3_weight"].max(),
        }
        rows.append(row)

    return pd.DataFrame(rows).sort_values(
        ["flow_type", "scenario_id", "horizon_days"]
    ).reset_index(drop=True)


def create_final_scenario_definitions(config: dict) -> pd.DataFrame:
    """Create the FE/FX scenario documentation table."""

    rows = []

    for specification in config["two_component_scenarios"]:
        rows.append(
            {
                "flow_type": specification["flow_type"],
                "scenario_id": specification["scenario_id"],
                "scenario_name": specification["scenario_name"],
                "description": specification["description"],
                "component_1": specification["primary"],
                "component_2": specification["comparison"],
                "component_3": None,
                "weight_method": "Expanding-window two-component WAPE selection",
            }
        )

    for specification in config["three_component_scenarios"]:
        rows.append(
            {
                "flow_type": specification["flow_type"],
                "scenario_id": specification["scenario_id"],
                "scenario_name": specification["scenario_name"],
                "description": specification["description"],
                "component_1": specification["components"][0],
                "component_2": specification["components"][1],
                "component_3": specification["components"][2],
                "weight_method": "Expanding-window three-component WAPE selection",
            }
        )

    return pd.DataFrame(rows)

# =============================================================================
# 8. PRICING OVERLAY SIMULATION
# =============================================================================

def prepare_pricing_bookings(
    pricing_bookings: pd.DataFrame,
    config: dict,
) -> pd.DataFrame:
    """
    Prepare multi-product booked-price records for historical snapshots.

    Historical booked prices act as a proxy for the quote prices that will be
    available to the future operational forecast.
    """

    df = pricing_bookings.copy()

    for column in [
        "createdAt",
        "cancelledAt",
        "entryDate",
        "exitDate",
    ]:
        df[column] = pd.to_datetime(
            df[column],
            errors="coerce",
        )

    df["planned_entry_date_ts"] = df["entryDate"].dt.normalize()
    df["planned_exit_date_ts"] = df["exitDate"].dt.normalize()
    df["booking_created_date_ts"] = df["createdAt"].dt.normalize()

    quantity = pd.to_numeric(
        df["productQuantity"],
        errors="coerce",
    ).replace(0, np.nan)

    duration = pd.to_numeric(
        df["planned_duration_days_calc"],
        errors="coerce",
    ).replace(0, np.nan)

    df["price_per_quantity_per_day"] = (
        pd.to_numeric(
            df["bookingTotal"],
            errors="coerce",
        )
        / quantity
        / duration
    )

    df = df[
        df["assetName"].isin(config["price_analysis_assets"])
        & df["createdAt"].notna()
        & df["planned_entry_date_ts"].notna()
        & df["price_per_quantity_per_day"].notna()
        & np.isfinite(df["price_per_quantity_per_day"])
        & df["price_per_quantity_per_day"].gt(0)
        & df["status"].ne("F")
    ].copy()

    return df


def get_pricing_bookings_active_as_of(
    bookings: pd.DataFrame,
    cutoff_timestamp: pd.Timestamp,
) -> pd.DataFrame:
    """
    Return bookings that existed and were still active at the cutoff.

    A booking later cancelled must remain visible at an earlier cutoff if the
    cancellation had not yet occurred.
    """

    cutoff_timestamp = pd.Timestamp(cutoff_timestamp)

    return bookings[
        bookings["createdAt"].le(cutoff_timestamp)
        & (
            bookings["cancelledAt"].isna()
            | bookings["cancelledAt"].gt(cutoff_timestamp)
        )
    ].copy()


def summarise_snapshot_prices(
    price_rows: pd.DataFrame,
    config: dict,
) -> dict:
    """
    Calculate FastPark price position from one snapshot population.
    """

    empty_result = {
        "fastpark_price_per_day": np.nan,
        "competitor_market_price_per_day": np.nan,
        "relative_price_index": np.nan,
        "fastpark_price_rank": np.nan,
        "fastpark_price_observations": 0,
        "competitor_price_observations": 0,
        "competitors_available": 0,
    }

    if price_rows.empty:
        return empty_result

    minimum_observations = (
        config["minimum_price_observations_per_asset"]
    )

    by_asset = (
        price_rows
        .groupby(
            "assetName",
            as_index=False,
        )
        .agg(
            median_price_per_day=(
                "price_per_quantity_per_day",
                "median",
            ),
            price_observations=(
                "bookingId",
                "nunique",
            ),
        )
    )

    by_asset = by_asset[
        by_asset["price_observations"].ge(
            minimum_observations
        )
    ].copy()

    fastpark = by_asset[
        by_asset["assetName"].eq(
            config["fastpark_asset_name"]
        )
    ].copy()

    competitors = by_asset[
        by_asset["assetName"].isin(
            config["competitor_asset_names"]
        )
    ].copy()

    if fastpark.empty:
        return empty_result

    if (
        competitors["assetName"].nunique()
        < config["minimum_competitors_available"]
    ):
        return empty_result

    fastpark_price = float(
        fastpark["median_price_per_day"].iloc[0]
    )

    market_price = float(
        competitors["median_price_per_day"].median()
    )

    if not np.isfinite(market_price) or market_price <= 0:
        return empty_result

    ranked_prices = pd.concat(
        [
            fastpark,
            competitors,
        ],
        ignore_index=True,
    )

    ranked_prices["price_rank"] = (
        ranked_prices["median_price_per_day"]
        .rank(
            method="min",
            ascending=True,
        )
    )

    fastpark_rank = float(
        ranked_prices.loc[
            ranked_prices["assetName"].eq(
                config["fastpark_asset_name"]
            ),
            "price_rank",
        ].iloc[0]
    )

    return {
        "fastpark_price_per_day": fastpark_price,
        "competitor_market_price_per_day": market_price,
        "relative_price_index": (
            fastpark_price / market_price
        ),
        "fastpark_price_rank": fastpark_rank,
        "fastpark_price_observations": int(
            fastpark["price_observations"].iloc[0]
        ),
        "competitor_price_observations": int(
            competitors["price_observations"].sum()
        ),
        "competitors_available": int(
            competitors["assetName"].nunique()
        ),
    }


def calculate_known_market_share(
    active_bookings: pd.DataFrame,
    target_date: pd.Timestamp,
    config: dict,
) -> dict:
    """
    Calculate the booking share visible for the exact target entry date.
    """

    target_date = pd.Timestamp(target_date).normalize()

    target_rows = active_bookings[
        active_bookings["planned_entry_date_ts"].eq(
            target_date
        )
    ].copy()

    counts = (
        target_rows
        .groupby("assetName")["bookingId"]
        .nunique()
    )

    fastpark_bookings = int(
        counts.get(
            config["fastpark_asset_name"],
            0,
        )
    )

    total_market_bookings = int(counts.sum())

    competitor_bookings = (
        total_market_bookings
        - fastpark_bookings
    )

    return {
        "known_fastpark_bookings": fastpark_bookings,
        "known_competitor_bookings": competitor_bookings,
        "known_total_market_bookings": total_market_bookings,
        "known_fastpark_share": (
            fastpark_bookings
            / total_market_bookings
            if total_market_bookings > 0
            else np.nan
        ),
    }


def build_single_pricing_snapshot(
    prepared_pricing: pd.DataFrame,
    target_date: pd.Timestamp,
    cutoff_timestamp: pd.Timestamp,
    horizon_days: int,
    config: dict,
) -> tuple[dict, pd.DataFrame]:
    """
    Reconstruct price position and market share at one historical cutoff.

    Search order:
        1. Exact target date using bookings created in the last 7 days.
        2. Exact target date using the last 14 days.
        3. Exact target date using the last 28 days.
        4. Nearby target dates using the same lookback sequence.
    """

    target_date = pd.Timestamp(target_date).normalize()
    cutoff_timestamp = pd.Timestamp(cutoff_timestamp)
    cutoff_date = cutoff_timestamp.normalize()

    active = get_pricing_bookings_active_as_of(
        bookings=prepared_pricing,
        cutoff_timestamp=cutoff_timestamp,
    )

    share_features = calculate_known_market_share(
        active_bookings=active,
        target_date=target_date,
        config=config,
    )

    selected_rows = pd.DataFrame()
    selected_lookback = np.nan
    selected_scope = None

    price_features = summarise_snapshot_prices(
        selected_rows,
        config,
    )

    target_scopes = [
        ("exact_target", 0),
        (
            "near_target",
            config["pricing_target_date_tolerance_days"],
        ),
    ]

    for target_scope, tolerance in target_scopes:

        lower_target = (
            target_date
            - pd.Timedelta(days=tolerance)
        )

        upper_target = (
            target_date
            + pd.Timedelta(days=tolerance)
        )

        for lookback_days in config[
            "pricing_created_lookback_days"
        ]:

            lower_created = (
                cutoff_date
                - pd.Timedelta(days=lookback_days)
            )

            candidate = active[
                active["booking_created_date_ts"].ge(
                    lower_created
                )
                & active["booking_created_date_ts"].le(
                    cutoff_date
                )
                & active["planned_entry_date_ts"].between(
                    lower_target,
                    upper_target,
                    inclusive="both",
                )
            ].copy()

            candidate_features = (
                summarise_snapshot_prices(
                    price_rows=candidate,
                    config=config,
                )
            )

            if pd.notna(
                candidate_features["relative_price_index"]
            ):
                selected_rows = candidate
                selected_lookback = lookback_days
                selected_scope = target_scope
                price_features = candidate_features
                break

        if pd.notna(
            price_features["relative_price_index"]
        ):
            break

    duration_detail = pd.DataFrame()

    if not selected_rows.empty:

        duration_records = []

        for (
            duration_band,
            duration_rows,
        ) in selected_rows.groupby(
            "planned_duration_band",
            observed=False,
        ):

            duration_price_features = (
                summarise_snapshot_prices(
                    price_rows=duration_rows,
                    config=config,
                )
            )

            duration_records.append(
                {
                    "target_date": target_date,
                    "cutoff_timestamp": cutoff_timestamp,
                    "horizon_days": horizon_days,
                    "planned_duration_band": str(
                        duration_band
                    ),
                    **duration_price_features,
                    "pricing_lookback_days": (
                        selected_lookback
                    ),
                    "pricing_target_scope": (
                        selected_scope
                    ),
                }
            )

        duration_detail = pd.DataFrame(
            duration_records
        )

    aggregate = {
        "target_date": target_date,
        "cutoff_timestamp": cutoff_timestamp,
        "horizon_days": int(horizon_days),
        **price_features,
        **share_features,
        "pricing_lookback_days": selected_lookback,
        "pricing_target_scope": selected_scope,
    }

    return aggregate, duration_detail


def build_pricing_snapshot_dataset(
    pricing_bookings: pd.DataFrame,
    test_dates: pd.DataFrame,
    horizons: list[int],
    config: dict,
) -> tuple[pd.DataFrame, pd.DataFrame]:
    """
    Build price and share features for every historical target and horizon.
    """

    prepared_pricing = prepare_pricing_bookings(
        pricing_bookings=pricing_bookings,
        config=config,
    )

    aggregate_rows = []
    duration_frames = []

    target_values = pd.to_datetime(
        test_dates["target_date"]
    ).dt.normalize()

    total_snapshots = (
        len(target_values)
        * len(horizons)
    )

    counter = 0

    print("\nBuilding historical pricing snapshots...")

    for target_date in target_values:
        for horizon_days in horizons:

            counter += 1

            cutoff_timestamp = (
                target_date
                - pd.Timedelta(days=horizon_days)
                + pd.Timedelta(hours=7)
            )

            print(
                f"\rPricing snapshots "
                f"{counter:,}/{total_snapshots:,} "
                f"| Target {target_date.date()} "
                f"| T-{horizon_days}",
                end="",
            )

            (
                aggregate,
                duration_detail,
            ) = build_single_pricing_snapshot(
                prepared_pricing=prepared_pricing,
                target_date=target_date,
                cutoff_timestamp=cutoff_timestamp,
                horizon_days=horizon_days,
                config=config,
            )

            aggregate_rows.append(aggregate)

            if not duration_detail.empty:
                duration_frames.append(
                    duration_detail
                )

    print()

    pricing_snapshots = pd.DataFrame(
        aggregate_rows
    )

    pricing_duration_detail = (
        pd.concat(
            duration_frames,
            ignore_index=True,
        )
        if duration_frames
        else pd.DataFrame()
    )

    return (
        pricing_snapshots,
        pricing_duration_detail,
    )

def create_winning_entry_base(
    final_results: pd.DataFrame,
    best_by_horizon: pd.DataFrame,
) -> pd.DataFrame:
    """
    Return the winning non-pricing FE forecast for every target/horizon.
    """

    winners = best_by_horizon[
        best_by_horizon["flow_type"].eq("ENTRY")
    ][
        [
            "horizon_days",
            "scenario_id",
            "scenario_name",
        ]
    ].rename(
        columns={
            "scenario_id": "base_scenario_id",
            "scenario_name": "base_scenario_name",
        }
    )

    entry_results = final_results[
        final_results["flow_type"].eq("ENTRY")
    ].copy()

    entry_results = entry_results.merge(
        winners,
        on="horizon_days",
        how="inner",
    )

    entry_results = entry_results[
        entry_results["scenario_id"].eq(
            entry_results["base_scenario_id"]
        )
    ].copy()

    return entry_results[
        [
            "target_date",
            "cutoff_timestamp",
            "horizon_days",
            "base_scenario_id",
            "base_scenario_name",
            "forecast_value",
            "actual_value",
        ]
    ].rename(
        columns={
            "forecast_value": "base_forecast",
        }
    )

def fit_pricing_factor_model(
    training: pd.DataFrame,
    feature_columns: list[str],
    minimum_observations: int,
) -> dict:
    """
    Fit a simple linear adjustment model for remaining pickup.

    The dependent variable is:

        actual remaining pickup
        -----------------------
        FE-expected remaining pickup

    The independent variables are relative price deviation, share deviation,
    or both, depending on PE1/PE2/PE3.
    """

    required_columns = (
        feature_columns
        + ["actual_remaining_pickup_factor"]
    )

    valid = training.dropna(
        subset=required_columns
    ).copy()

    if len(valid) < minimum_observations:
        return {
            "available": False,
            "observations": len(valid),
            "intercept": np.nan,
            "coefficients": {},
        }

    x = (
        valid[feature_columns]
        .astype(float)
        .to_numpy()
    )

    y = (
        valid["actual_remaining_pickup_factor"]
        .astype(float)
        .to_numpy()
    )

    design_matrix = np.column_stack(
        [
            np.ones(len(valid)),
            x,
        ]
    )

    coefficients, _, _, _ = np.linalg.lstsq(
        design_matrix,
        y,
        rcond=None,
    )

    return {
        "available": True,
        "observations": len(valid),
        "intercept": float(coefficients[0]),
        "coefficients": {
            feature: float(value)
            for feature, value in zip(
                feature_columns,
                coefficients[1:],
            )
        },
    }

def run_pricing_overlay_backtest(
    winning_entry_base: pd.DataFrame,
    pricing_snapshots: pd.DataFrame,
    config: dict,
) -> pd.DataFrame:
    """
    Run PE1-PE3 on the winning FE model at each horizon.
    """

    base = winning_entry_base.merge(
        pricing_snapshots,
        on=[
            "target_date",
            "cutoff_timestamp",
            "horizon_days",
        ],
        how="left",
    )

    base["relative_price_index"] = (
        base["relative_price_index"]
        .clip(
            lower=(
                config[
                    "minimum_relative_price_index"
                ]
            ),
            upper=(
                config[
                    "maximum_relative_price_index"
                ]
            ),
        )
    )

    base["relative_price_deviation"] = (
        base["relative_price_index"]
        - 1.0
    )

    base["base_remaining_pickup"] = (
        base["base_forecast"]
        - base["known_fastpark_bookings"]
    ).clip(lower=0)

    base["actual_remaining_pickup"] = (
        base["actual_value"]
        - base["known_fastpark_bookings"]
    ).clip(lower=0)

    base["actual_remaining_pickup_factor"] = (
        base["actual_remaining_pickup"]
        / base["base_remaining_pickup"].replace(
            0,
            np.nan,
        )
    ).clip(
        lower=config["minimum_pricing_factor"],
        upper=config["maximum_pricing_factor"],
    )

    output_rows = []

    for (
        horizon_days,
        horizon_frame,
    ) in base.groupby("horizon_days"):

        horizon_frame = (
            horizon_frame
            .sort_values("target_date")
            .copy()
        )

        for current in horizon_frame.itertuples(
            index=False
        ):

            cutoff_date = pd.Timestamp(
                current.cutoff_timestamp
            ).normalize()

            historical = horizon_frame[
                horizon_frame["target_date"].lt(
                    cutoff_date
                )
                & horizon_frame[
                    "base_remaining_pickup"
                ].ge(
                    config["minimum_remaining_pickup"]
                )
            ].copy()

            historical_share_baseline = (
                historical[
                    "known_fastpark_share"
                ].median()
            )

            current_share = (
                current.known_fastpark_share
            )

            if (
                pd.notna(historical_share_baseline)
                and historical_share_baseline > 0
            ):
                share_deviation = (
                    current_share
                    - historical_share_baseline
                )
            else:
                share_deviation = np.nan

            historical["share_deviation"] = (
                historical["known_fastpark_share"]
                - historical[
                    "known_fastpark_share"
                ].expanding().median().shift(1)
            )

            for specification in config[
                "pricing_scenarios"
            ]:

                feature_columns = (
                    specification["features"]
                )

                model = fit_pricing_factor_model(
                    training=historical,
                    feature_columns=feature_columns,
                    minimum_observations=(
                        config[
                            "minimum_pricing_training_observations"
                        ]
                    ),
                )

                current_features = {
                    "relative_price_deviation": (
                        current.relative_price_deviation
                    ),
                    "share_deviation": share_deviation,
                }

                features_available = all(
                    pd.notna(
                        current_features[feature]
                    )
                    for feature in feature_columns
                )

                if (
                    model["available"]
                    and features_available
                    and current.base_remaining_pickup
                    >= config["minimum_remaining_pickup"]
                ):

                    pricing_factor = model["intercept"]

                    for feature in feature_columns:
                        pricing_factor += (
                            model["coefficients"][feature]
                            * current_features[feature]
                        )

                    pricing_factor = float(
                        np.clip(
                            pricing_factor,
                            config[
                                "minimum_pricing_factor"
                            ],
                            config[
                                "maximum_pricing_factor"
                            ],
                        )
                    )

                    adjusted_forecast = (
                        current.known_fastpark_bookings
                        + pricing_factor
                        * current.base_remaining_pickup
                    )

                    pricing_used = True

                else:

                    pricing_factor = 1.0
                    adjusted_forecast = (
                        current.base_forecast
                    )
                    pricing_used = False

                error = (
                    adjusted_forecast
                    - current.actual_value
                )

                output_rows.append(
                    {
                        "target_date": (
                            current.target_date
                        ),
                        "cutoff_timestamp": (
                            current.cutoff_timestamp
                        ),
                        "horizon_days": int(
                            horizon_days
                        ),
                        "horizon_label": (
                            f"T-{int(horizon_days)}"
                        ),
                        "flow_type": "ENTRY",
                        "scenario_id": (
                            specification[
                                "scenario_id"
                            ]
                        ),
                        "scenario_name": (
                            specification[
                                "scenario_name"
                            ]
                        ),
                        "base_scenario_id": (
                            current.base_scenario_id
                        ),
                        "base_scenario_name": (
                            current.base_scenario_name
                        ),
                        "base_forecast": (
                            current.base_forecast
                        ),
                        "known_fastpark_bookings": (
                            current.known_fastpark_bookings
                        ),
                        "base_remaining_pickup": (
                            current.base_remaining_pickup
                        ),
                        "fastpark_price_per_day": (
                            current.fastpark_price_per_day
                        ),
                        "competitor_market_price_per_day": (
                            current.competitor_market_price_per_day
                        ),
                        "relative_price_index": (
                            current.relative_price_index
                        ),
                        "relative_price_deviation": (
                            current.relative_price_deviation
                        ),
                        "known_fastpark_share": (
                            current.known_fastpark_share
                        ),
                        "historical_share_baseline": (
                            historical_share_baseline
                        ),
                        "share_deviation": (
                            share_deviation
                        ),
                        "known_competitor_bookings": (
                            current.known_competitor_bookings
                        ),
                        "known_total_market_bookings": (
                            current.known_total_market_bookings
                        ),
                        "fastpark_price_rank": (
                            current.fastpark_price_rank
                        ),
                        "competitors_available": (
                            current.competitors_available
                        ),
                        "pricing_factor": (
                            pricing_factor
                        ),
                        "pricing_used": pricing_used,
                        "pricing_training_observations": (
                            model["observations"]
                        ),
                        "pricing_intercept": (
                            model["intercept"]
                        ),
                        "price_coefficient": (
                            model["coefficients"].get(
                                "relative_price_deviation",
                                np.nan,
                            )
                        ),
                        "share_coefficient": (
                            model["coefficients"].get(
                                "share_deviation",
                                np.nan,
                            )
                        ),
                        "forecast_value": (
                            adjusted_forecast
                        ),
                        "actual_value": (
                            current.actual_value
                        ),
                        "error": error,
                        "absolute_error": abs(error),
                        "squared_error": error ** 2,
                    }
                )

    return pd.DataFrame(output_rows)

def score_pricing_scenarios(
    pricing_results: pd.DataFrame,
) -> pd.DataFrame:
    """
    Score PE1-PE3 and compare each with the winning FE base.
    """

    if pricing_results.empty:
        return pd.DataFrame()

    rows = []

    grouping = [
        "scenario_id",
        "scenario_name",
        "horizon_days",
    ]

    for (
        scenario_id,
        scenario_name,
        horizon_days,
    ), group in pricing_results.groupby(
        grouping
    ):

        pricing_metrics = calculate_candidate_metrics(
            actual=group["actual_value"],
            forecast=group["forecast_value"],
        )

        base_metrics = calculate_candidate_metrics(
            actual=group["actual_value"],
            forecast=group["base_forecast"],
        )

        rows.append(
            {
                "flow_type": "ENTRY",
                "scenario_id": scenario_id,
                "scenario_name": scenario_name,
                "horizon_days": horizon_days,
                "horizon_label": (
                    f"T-{horizon_days}"
                ),
                **pricing_metrics,
                "base_wape_pct": (
                    base_metrics["wape_pct"]
                ),
                "base_mae": (
                    base_metrics["mae"]
                ),
                "wape_improvement_points": (
                    base_metrics["wape_pct"]
                    - pricing_metrics["wape_pct"]
                ),
                "mae_improvement": (
                    base_metrics["mae"]
                    - pricing_metrics["mae"]
                ),
                "pricing_usage_pct": (
                    group["pricing_used"].mean()
                    * 100
                ),
                "average_pricing_factor": (
                    group["pricing_factor"].mean()
                ),
                "average_relative_price_index": (
                    group[
                        "relative_price_index"
                    ].mean()
                ),
                "average_known_fastpark_share": (
                    group[
                        "known_fastpark_share"
                    ].mean()
                ),
            }
        )

    return (
        pd.DataFrame(rows)
        .sort_values(
            [
                "horizon_days",
                "wape_pct",
                "scenario_id",
            ]
        )
        .reset_index(drop=True)
    )

# =============================================================================
# 9. EXPORT
# =============================================================================

def format_workbook(workbook) -> None:
    """Apply practical formatting to every sheet."""

    from openpyxl.styles import Font
    from openpyxl.utils import get_column_letter

    for worksheet in workbook.worksheets:
        worksheet.freeze_panes = "A2"

        if worksheet.max_row > 1:
            worksheet.auto_filter.ref = worksheet.dimensions

        for cell in worksheet[1]:
            cell.font = Font(bold=True)

        for column_cells in worksheet.columns:
            values = [
                len(str(cell.value))
                for cell in column_cells
                if cell.value is not None
            ]

            maximum_length = max(values) if values else 10
            column_letter = get_column_letter(column_cells[0].column)
            worksheet.column_dimensions[column_letter].width = min(
                max(maximum_length + 2, 10),
                60,
            )


def export_final_scenario_results(
    component_results: pd.DataFrame,
    final_results: pd.DataFrame,
    performance: pd.DataFrame,
    best_by_horizon: pd.DataFrame,
    weight_summary: pd.DataFrame,
    definitions: pd.DataFrame,
    pricing_snapshots: pd.DataFrame,
    pricing_duration_detail: pd.DataFrame,
    pricing_results: pd.DataFrame,
    pricing_performance: pd.DataFrame,
    output_path: Path,
) -> Path:
    """Export all FE/FX results to Excel."""

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)

    entry_performance = performance[performance["flow_type"].eq("ENTRY")]
    exit_performance = performance[performance["flow_type"].eq("EXIT")]

    entry_results = final_results[final_results["flow_type"].eq("ENTRY")]
    exit_results = final_results[final_results["flow_type"].eq("EXIT")]

    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        best_by_horizon.to_excel(
            writer,
            sheet_name="Best Final By Horizon",
            index=False,
        )

        entry_performance.to_excel(
            writer,
            sheet_name="FE Performance",
            index=False,
        )

        exit_performance.to_excel(
            writer,
            sheet_name="FX Performance",
            index=False,
        )

        weight_summary.to_excel(
            writer,
            sheet_name="Weight Stability",
            index=False,
        )

        entry_results.to_excel(
            writer,
            sheet_name="FE Forecast Detail",
            index=False,
        )

        exit_results.to_excel(
            writer,
            sheet_name="FX Forecast Detail",
            index=False,
        )

        definitions.to_excel(
            writer,
            sheet_name="Final Scenario Definitions",
            index=False,
        )

        component_results.to_excel(
            writer,
            sheet_name="Source Components",
            index=False,
        )

        pricing_snapshots.to_excel(
            writer,
            sheet_name="Pricing Snapshot Detail",
            index=False,
        )

        pricing_duration_detail.to_excel(
            writer,
            sheet_name="Pricing by Duration",
            index=False,
        )

        pricing_results.to_excel(
            writer,
            sheet_name="PE Forecast Detail",
            index=False,
        )

        pricing_performance.to_excel(
            writer,
            sheet_name="Pricing vs FE Base",
            index=False,
        )

        format_workbook(writer.book)

    print(f"Exported FE/FX simulation workbook: {output_path}")
    return output_path


# =============================================================================
# 10. CONSOLE SUMMARY
# =============================================================================

def print_final_summary(
    performance: pd.DataFrame,
    best_by_horizon: pd.DataFrame,
    weight_summary: pd.DataFrame,
) -> None:
    """Print the final FE/FX tournament summary."""

    print("\n" + "=" * 90)
    print("FASTPARK FINAL FE/FX SCENARIO RESULTS")
    print("=" * 90)

    print("\nBEST FINAL MODEL BY HORIZON")
    print("-" * 90)
    print(
        best_by_horizon[
            [
                "flow_type",
                "horizon_label",
                "scenario_id",
                "scenario_name",
                "wape_pct",
                "mae",
                "rmse",
                "bias",
                "coverage_pct",
            ]
        ].to_string(index=False)
    )

    print("\nOVERALL AVERAGE HORIZON RANK")
    print("-" * 90)

    overall = (
        performance
        .groupby(["flow_type", "scenario_id", "scenario_name"], as_index=False)
        .agg(
            average_wape_pct=("wape_pct", "mean"),
            average_mae=("mae", "mean"),
            average_bias=("bias", "mean"),
            average_rank=("wape_rank", "mean"),
            horizon_wins=("wape_rank", lambda values: int((values == 1).sum())),
        )
        .sort_values(["flow_type", "average_rank", "average_wape_pct"])
    )

    print(overall.to_string(index=False))

    print("\nWEIGHT-SELECTION COVERAGE")
    print("-" * 90)
    coverage = (
        weight_summary
        .groupby(["flow_type", "scenario_id"], as_index=False)
        .agg(
            expanding_selected_forecasts=("expanding_selected_forecasts", "sum"),
            fallback_forecasts=("fallback_forecasts", "sum"),
        )
    )
    print(coverage.to_string(index=False))


# =============================================================================
# 11. MAIN EXECUTION
# =============================================================================

if __name__ == "__main__":
    start_time = time.perf_counter()

    print("=" * 90)
    print("FASTPARK FINAL FE/FX SCENARIO SIMULATION")
    print("EXPANDING-WINDOW WEIGHT SELECTION")
    print("=" * 90)

    config = get_final_scenario_config()

    component_results, simulation_context = (
        get_component_results(config)
    )
    component_time = step(start_time, "Reloaded data and reran FE/FX source components")

    final_results = run_final_scenario_tournament(
        component_results=component_results,
        config=config,
    )
    tournament_time = step(
        component_time,
        f"Completed FE/FX tournament ({len(final_results):,} rows)",
    )

    performance = score_final_scenarios(final_results)
    best_by_horizon = create_best_final_by_horizon(performance)
    weight_summary = create_weight_summary(final_results)
    definitions = create_final_scenario_definitions(config)

    if config["enable_pricing_simulation"]:

        (
            pricing_snapshots,
            pricing_duration_detail,
        ) = build_pricing_snapshot_dataset(
            pricing_bookings=(
                simulation_context[
                    "pricing_bookings"
                ]
            ),
            test_dates=(
                simulation_context[
                    "test_dates"
                ]
            ),
            horizons=(
                simulation_context[
                    "horizons"
                ]
            ),
            config=config,
        )

        winning_entry_base = (
            create_winning_entry_base(
                final_results=final_results,
                best_by_horizon=best_by_horizon,
            )
        )

        pricing_results = (
            run_pricing_overlay_backtest(
                winning_entry_base=(
                    winning_entry_base
                ),
                pricing_snapshots=(
                    pricing_snapshots
                ),
                config=config,
            )
        )

        pricing_performance = (
            score_pricing_scenarios(
                pricing_results
            )
        )

    else:

        pricing_snapshots = pd.DataFrame()
        pricing_duration_detail = pd.DataFrame()
        pricing_results = pd.DataFrame()
        pricing_performance = pd.DataFrame()

    scoring_time = step(tournament_time, "Scored and ranked FE/FX scenarios")

    output_path = export_final_scenario_results(
        component_results=component_results,
        final_results=final_results,
        performance=performance,
        best_by_horizon=best_by_horizon,
        weight_summary=weight_summary,
        definitions=definitions,
        pricing_snapshots=pricing_snapshots,
        pricing_duration_detail=pricing_duration_detail,
        pricing_results=pricing_results,
        pricing_performance=pricing_performance,
        output_path=config["output_path"],
    )

    export_time = step(scoring_time, f"Exported workbook: {output_path}")

    print_final_summary(
        performance=performance,
        best_by_horizon=best_by_horizon,
        weight_summary=weight_summary,
    )

    step(export_time, "FastPark final FE/FX simulation complete")
